yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите описание поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста, постов'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_posts',
        verbose_name='Группа поста, постов',
        help_text='Выберите подходящую группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:settings.OUTPUT]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:settings.INTRODUCTION]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post
from django.conf import settings
from django.core.paginator import Paginator

User = get_user_model()


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.PAGINATION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    paginator = Paginator(posts, settings.PAGINATION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    post_count = posts.count()
    paginator = Paginator(posts, settings.PAGINATION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'post_count': post_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('post').filter(post=post_id)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = (
        Post.objects.filter(author__following__user=request.user))
    paginator = Paginator(posts, settings.PAGINATION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)

    if request.user == author:
        return redirect(
            'posts:profile',
            username=username
        )
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}

{% block title %}
{% if is_edit %}Редактировать пост
{% else %}
Создать новый пост
{% endif %}
{% endblock %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
        {% if is_edit %}Редактировать пост{% else %}
        Создать новый пост
        {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
                    enctype="multipart/form-data"
                    action="{% if is_edit %}{% url 'posts:post_edit' form.instance.pk %}{% else %}{% url 'posts:post_create' %}{% endif %}">
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки{% endblock %}
{% block content %}
  <div class="container py-5">
    <h3>Подписки:</h3>
    {% if user.is_authenticated %}
    <div class="row my-3">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link {% if view.name == 'posts:index' %}active{% endif %}"
             href="{% url 'posts:index' %}">Все авторы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view.name == 'posts:follow_index' %}active{% endif %}"
             href="{% url 'posts:follow_index' %}">Избранные авторы</a>
        </li>
      </ul>
    </div>
    {% endif %}
    {% for post in page_obj %}
      <article>
         <ul>
            <br>
           <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
         </ul>
         {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
         {% endthumbnail %}
         <p>{{ post.text }}</p>
         <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
      {% if post.group.slug %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %} Записи сообщества: {{ group.title }} {% endblock %}

{% block content %}

  <h1> {{ group.title }}  </h1>
    <p> {{ group.description }} </p>

    {% for post in page_obj %}
        <article>
          <ul>
            <br>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
             Дата публикации: {{ post.pub_date|date:"d E Y" }}
           </li>
         </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
         <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
      
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
 
    {% if not forloop.last %}<hr>{% endif %}
    
    {% endfor %}
      
    {% include 'includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %} Это главная страница проекта Yatube {% endblock %}

{% block content %}

{% load cache %}
{% cache 20 index_page with page_obj %}
  
  <h1> Последние обновления на сайте </h1>
    {% if user.is_authenticated %}
      <div class="row my-3">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link {% if view.name == 'posts:index' %}active{% endif %}"
               href="{% url 'posts:index' %}">Все авторы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view.name == 'posts:follow_index' %}active{% endif %}"
               href="{% url 'posts:follow_index' %}">Избранные авторы</a>
          </li>
        </ul>
      </div>
    {% endif %}
  
    {% for post in page_obj %}
            <article>
         <ul>
            <br>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
             Дата публикации: {{ post.pub_date|date:"d E Y" }}
           </li>
         </ul>
         {% thumbnail post.image "960x339" crop="center" upscale=True as image %}
           <img class="card-img my-2" src="{{ image.url }}">
         {% endthumbnail %}
         <p>{{ post.text }}</p>
         <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
      
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">| все записи группы</a>
      {% endif %} 
 
    {% if not forloop.last %}<hr>{% endif %}
    
    {% endfor %}

    {% endcache %}

  {% include 'includes/paginator.html' %}

{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}

{% block content %}


<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item">
        Группа: {{ post.group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
      </li>
      {% endif %}

      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:<span >{{ post.author.posts.all.count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <br>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    {% if post.author.pk == user.pk %}
    <a class="btn btn-primary"
      href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
    {% endif %}

    {% load user_filters %}

    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </article>
</div>

{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}

{% block content %}
<div class="mb-5"></div>
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ post_count }} </h3>   

  {% if request.user != author %}
      {% if following %}
          <a class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}"
              role="button">Отписаться</a>
      {% else %}
          <a class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}"
              role="button">Подписаться</a>
      {% endif %}
  {% endif %}
{% for post in page_obj %}
<article>
  <ul>
    <br>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
</article>
{% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}      
{% if not forloop.last %}<hr>{% endif %}

{% endfor %}

{% include 'includes/paginator.html' %}

{% endblock %} 